config/routes.rb
ServIng::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :properties

  root :to => "home#index"
  match "/soluciones" => "home#soluciones"
  match "/proyectos" => "home#proyectos"
  match "/proyectos/:project_id" => "home#proyecto"
  match "/contacto" => "home#contacto"

  match "/pixel" => "home#pixel"
  match "/arpel" => "home#arpel"
  match "/coolbar" => "home#coolbar"
  match "/gsport" => "home#gsport"
  match "/cruzmorel" => "home#cruzmorel"
  match "/cymsupplyparts" => "home#cymsupplyparts"
  match "/escuela" => "home#escuela"
  match "/almacen" => "home#almacen"
  match "/apartamentos" => "home#apartamentos"

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :author, :email, :inquire
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :path, :property_id, :path_cache, :remove_path
  belongs_to :property
  mount_uploader :path, ImageUploader
end

app/models/property.rb
class Property < ActiveRecord::Base
    TYPE_OPTIONS = %w[casa apt local solar]
  attr_accessible :picture_ids, :bathrooms, :description, :location, :mts, :price, :purpose, :rooms, :title, :property_id, :parkingspace, :picture_attributes

  has_many :pictures, :dependent => :destroy

  validates :bathrooms, :description, :location, :mts, :price, :purpose, :rooms, :title, :presence => true
  validates_length_of :description, :minimum => 5
  validates_length_of :description, :maximum => 1000
  validates_numericality_of :price, :rooms, :mts, :bathrooms

  def humanize_price
    "RD$ #{ActionController::Base.helpers.number_to_currency(self.price, :precision => 0)}"
  end

  def normalize_meters
    "#{self.mts.to_i}"
  end

end

#options_from_collection_for_select(Property.TYPE_OPTIONS)

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def proyectos

  end

  def proyecto
    @project_id = params[:project_id]
    case @project_id
    when "1"
      redirect_to "/pixel"
    when "2"
      redirect_to "/arpel"
    when "3"
      redirect_to "/coolbar"
    when "4"
      redirect_to "/gsport"
    when "5"
      redirect_to "/cruzmorel"
    when "6"
      redirect_to "/cymsupplyparts"
    when "7"
      redirect_to "/escuela"
    when "8"
      redirect_to "/almacen"
    when "9"
      redirect_to "/apartamentos"
    end
  end

  def pixel
  end

  def arpel
  end

  def coolbar
  end

  def gsport
  end

  def cruzmorel
  end

  def cymsupplyparts
  end

  def escuela
  end

  def almacen
  end

  def apartamentos
  end

  def soluciones

  end

  def contacto

  end
  
end

app/controllers/message_controller.rb
class MessageController < ApplicationController

  def edit
    @message = Property.find(params[:id])
  end

  def create
    @message = message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'El mensaje se ha creado éxitosamente' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @message = message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'El mensaje fué cambiado éxitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @message = message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.order("created_at").page(params[:page]).per_page(1)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }

    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/home/almacen.html.haml
#content
  .wrapper
    / Used for ajax transition
    .old
    / start new container
    .new
      / NOTICE: Do NOT edit above. Keep the structure before this part as-is.
      / ////////////////////////////////////////////////////////
      / start target container, this part is loaded dynamically!
      .target.docked
        .container.subheader
          %header.row
            %hgroup
              %h1.headline
                %span Remodelación Almacen
        .gap
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .works.twelve.columns.phone-four.fourCols
                %h3 Remodelación discoteca Mangú Puerto Plata.
                / Adding gallery images. We use resized thumbnails here for better performance, but it’s not necessary
                #galleria
                  %a{:href => "assets/proyectos/Almacen00-s.jpg"}
                    %img{"data-description" => "Remodelación de almacen"}
                  %a{:href => "assets/proyectos/Almacen01-s.jpg"}
                    %img{"data-description" => "”Remodelación de almacen", :src => "assets/proyectos-thumbs/Almacen01-s.jpg"}
                  %a{:href => "assets/proyectos/Almacen02-s.jpg"}
                    %img{"data-description" => "Remodelación de almacen", "data-title" => "Araña", :src => "assets/proyectos-thumbs/Almacen02-s.jpg"}
                  %a{:href => "assets/proyectos/Almacen03-s.jpg"}
                    %img{"data-title" => "Remodelación de almacen", :src => "assets/proyectos-thumbs/Almacen03-s.jpg"}
                  %a{:href => "assets/proyectos/Almacen04-s.jpg"}
                    %img{"data-title" => "Remodelación de almacen", :src => "assets/proyectos-thumbs/Almacen04-s.jpg"}
                :javascript
                  // Load the classic theme
                  Galleria.loadTheme('assets/galleria.classic.min.js');

                  // Initialize Galleria
                  Galleria.run('#galleria');

                  
            .row.copy
              %p
                © Todos los derechos reservados, Serv-Ing 2013 -
                %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                Powered by
                %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree

app/views/home/apartamentos.html.haml
#content
  .wrapper
    .old
    .new
      .target.docked
        .container.subheader
          %header.row
            %hgroup
              %h1.headline
                %span Mantenimiento de Apartamentos
        .gap
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .works.twelve.columns.phone-four.fourCols
                %h3 Remodelación discoteca Mangú Puerto Plata.
                / Adding gallery images. We use resized thumbnails here for better performance, but it’s not necessary
                #galleria
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Locomotives-Roundhouse2.jpg/800px-Locomotives-Roundhouse2.jpg"}
                    %img{"data-description" => "Steam locomotives of the Chicago & North Western Railway.", "data-title" => "Locomotives Roundhouse", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Locomotives-Roundhouse2.jpg/100px-Locomotives-Roundhouse2.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Icebergs_in_the_High_Arctic_-_20050907.jpg/1000px-Icebergs_in_the_High_Arctic_-_20050907.jpg"}
                    %img{"data-description" => "”The debris loading isn't particularly extensive, but the color is usual.”", "data-title" => "Icebergs in the High Arctic", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Icebergs_in_the_High_Arctic_-_20050907.jpg/100px-Icebergs_in_the_High_Arctic_-_20050907.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Ara%C3%B1a._A_Estrada%2C_Galiza._02.jpg/1000px-Ara%C3%B1a._A_Estrada%2C_Galiza._02.jpg"}
                    %img{"data-description" => "Xysticus cristatus, A Estrada, Galicia, Spain", "data-title" => "Araña", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Ara%C3%B1a._A_Estrada%2C_Galiza._02.jpg/100px-Ara%C3%B1a._A_Estrada%2C_Galiza._02.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/9104_-_Milano_-_Museo_storia_naturale_-_Fluorite_-_Foto_Giovanni_Dall%27Orto_22-Apr-2007.jpg/1000px-9104_-_Milano_-_Museo_storia_naturale_-_Fluorite_-_Foto_Giovanni_Dall%27Orto_22-Apr-2007.jpg"}
                    %img{"data-title" => "Museo storia naturale", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/9104_-_Milano_-_Museo_storia_naturale_-_Fluorite_-_Foto_Giovanni_Dall%27Orto_22-Apr-2007.jpg/100px-9104_-_Milano_-_Museo_storia_naturale_-_Fluorite_-_Foto_Giovanni_Dall%27Orto_22-Apr-2007.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Grj%C3%B3tagj%C3%A1_caves_in_summer_2009_%282%29.jpg/1000px-Grj%C3%B3tagj%C3%A1_caves_in_summer_2009_%282%29.jpg"}
                    %img{"data-title" => "Grjótagjá caves in summer 2009", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Grj%C3%B3tagj%C3%A1_caves_in_summer_2009_%282%29.jpg/100px-Grj%C3%B3tagj%C3%A1_caves_in_summer_2009_%282%29.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/9/90/20091128_Loutra_Thermes_Xanthi_Thrace_Greece_2.jpg/1000px-20091128_Loutra_Thermes_Xanthi_Thrace_Greece_2.jpg"}
                    %img{"data-description" => "Xanthi hot-spa springs, Xanthi Prefecture, Greece", "data-title" => "Thermes", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/9/90/20091128_Loutra_Thermes_Xanthi_Thrace_Greece_2.jpg/100px-20091128_Loutra_Thermes_Xanthi_Thrace_Greece_2.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Polish_Army_Ko%C5%82obrzeg_077.JPG/1024px-Polish_Army_Ko%C5%82obrzeg_077.JPG"}
                    %img{"data-description" => "A display of the Polish Army. Both the soldier, and the vehicle belong to the 7th Pomeranian Coastal Defence Brigade, a part of the Szczecin-based 12th Mechanized Division ”Bolesław Krzywousty”", "data-title" => "Polish Army Kołobrzeg", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Polish_Army_Ko%C5%82obrzeg_077.JPG/100px-Polish_Army_Ko%C5%82obrzeg_077.JPG"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/20100213_Zlatograd_Bulgaria_3.jpg/1024px-20100213_Zlatograd_Bulgaria_3.jpg"}
                    %img{"data-title" => "Zlatograd Bulgaria", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/20100213_Zlatograd_Bulgaria_3.jpg/100px-20100213_Zlatograd_Bulgaria_3.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/FEMA_-_5399_-_Photograph_by_Andrea_Booher_taken_on_09-28-2001_in_New_York.jpg/1024px-FEMA_-_5399_-_Photograph_by_Andrea_Booher_taken_on_09-28-2001_in_New_York.jpg"}
                    %img{"data-description" => "New York, NY, September 28, 2001 -- Debris on surrounding roofs at the site of the World Trade Center. Photo by Andrea Booher/ FEMA News Photo", "data-title" => "09-28-2001 in New York City", :src => "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/FEMA_-_5399_-_Photograph_by_Andrea_Booher_taken_on_09-28-2001_in_New_York.jpg/100px-FEMA_-_5399_-_Photograph_by_Andrea_Booher_taken_on_09-28-2001_in_New_York.jpg"}
                  %a{:href => "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Antennae%2C_Hubble_images.jpg/1024px-Antennae%2C_Hubble_images.jpg"}
                    %img{:src => "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Antennae%2C_Hubble_images.jpg/100px-Antennae%2C_Hubble_images.jpg"}
                  %p.cred
                    Made by
                    = succeed "." do
                      %a{:href => "http://galleria.aino.se"} Galleria
                :javascript
                  // Load the classic theme
                  Galleria.loadTheme('assets/galleria.classic.min.js');

                  // Initialize Galleria
                  Galleria.run('#galleria');

                  
            .row.copy
              %p
                © Todos los derechos reservados, Serv-Ing 2013 -
                %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                Powered by
                %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree

app/views/home/arpel.html.haml
#content
  .wrapper
    / Used for ajax transition
    .old
    / start new container
    .new
      / NOTICE: Do NOT edit above. Keep the structure before this part as-is.
      / ////////////////////////////////////////////////////////
      / start target container, this part is loaded dynamically!
      .target.docked
        .container.subheader
          %header.row
            %hgroup
              %h1.headline
                %span Torre Arpel
        .gap
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .works.twelve.columns.phone-four.fourCols
                %h3 Remodelación discoteca Mangú Puerto Plata.
                / Adding gallery images. We use resized thumbnails here for better performance, but it’s not necessary
                #galleria
                  %a{:href => "assets/proyectos/Arpel00.jpg"}
                    %img{"data-description" => "Remodelación, apartamentos Arpel"}
                  %a{:href => "assets/proyectos/Arpel01.jpg"}
                    %img{"data-description" => "”Remodelación, apartamentos Arpel", :src => "assets/proyectos-thumbs/Arpel01.jpg"}
                  %a{:href => "assets/proyectos/Arpel02.jpg"}
                    %img{"data-description" => "Remodelación, apartamentos Arpel", "data-title" => "Araña", :src => "assets/proyectos-thumbs/Arpel02.jpg"}
                  %a{:href => "assets/proyectos/Arpel03.jpg"}
                    %img{"data-title" => "Remodelación, apartamentos Arpel", :src => "assets/proyectos-thumbs/Arpel03.jpg"}
                  %a{:href => "assets/proyectos/Arpel04.jpg"}
                    %img{"data-title" => "Remodelación, apartamentos Arpel", :src => "assets/proyectos-thumbs/Arpel04.jpg"}
                  %a{:href => "assets/proyectos/Arpel05.jpg"}
                    %img{"data-description" => "Remodelación, apartamentos Arpel", "data-title" => "Thermes", :src => "assets/proyectos-thumbs/Arpel05.jpg"}
                  %p.cred
                    Made by
                    = succeed "." do
                      %a{:href => "http://galleria.aino.se"} Galleria
                :javascript
                  // Load the classic theme
                  Galleria.loadTheme('assets/galleria.classic.min.js');

                  // Initialize Galleria
                  Galleria.run('#galleria');

                  
            .row.copy
              %p
                © Todos los derechos reservados, Serv-Ing 2013 -
                %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                Powered by
                %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree

app/views/home/contacto.html.haml
#content
  .wrapper
    .old
    .new
      .target.docked.contact{"data-address" => "18.450311,-69.935748", "data-zoom" => "16"}
        .container.subheader
          %header.row
            %hgroup
              %h1.headline
                %span Contactanos
        .gap
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .six.columns
                %h4 Déjanos saber tu opinion
                .contactForm
                  // Working on this part ! = form_for(@message) do |f|
                  .fields
                    /= f.text_field :nombre, {:placeholder => 'Nombre', :class => 'nombre.input-text'}
                    %input#nombre.input-text{:autocomplete => "off", :name => "nombre", :placeholder => "Nombre", :required => "", :type => "text"}
                      %input#email.input-text{:autocomplete => "off", :name => "Email", :placeholder => "Email", :required => "", :type => "email"}
                  .area
                    %textarea#mensaje.input-text{:name => "mensaje", :placeholder => "Mensaje", :required => ""}
                  .row
                    .seven.phone-four.columns.feedback
                      .alert-box.success
                        Yay! The Mensaje was sent. Thank you!
                        %a.close{:href => "#", :target => "_self"} ×
                      .alert-box.warning
                        Hey, fill out the fields correctly!
                        %a.close{:href => "#"} ×
                      .alert-box.error
                        Whoops! It seems like some error occurred!
                        %a.close{:href => "#", :target => "_self"} ×
                    .four.phone-four.columns
                      %input#submit.nice.small.radius.green.button{:type => "button", :value => "Enviar"}
              .three.columns
                %h4 Estamos aquí
                %p
                  Av. José Contreras #290,
                  Sector Honduras,
                  Santo Domingo, Repúblic Dominicana
              .three.columns
                %h4 Contactanos
                %ul.contactInfo
                  %li
                    %span.pin
                    %div
                      Teléfono (809) 435 9569
                      %br/
                      Fax (809) 903 1074
                      %br/
                  %li
                    %span.iphone
                    %div (809) 902 0074
                  %li
                    %span.Email
                    %div
                      %a{:href => "mailto:gary@serv-ing.com", :target => "_blank"} gary@serv-ing.com
                    %div
                      %a{:href => "mailto:freddy@serv-ing.com", :target => "_blank"} freddy@serv-ing.com
            .row.copy
              %p
                © Todos los derechos reservados, Serv-Ing 2013 -
                %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                Powered by
                %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree

app/views/layouts/_header.html.haml
/ fullscreen background slideshow start
#bg.background
  %ul.bg-gallery{"data-delay" => "8"}
    %li{"data-image" => "assets/slides/01.jpg"}
      %span
    %li{"data-image" => "assets/slides/02.jpg"}
      %span
/ fullscreen background slideshow end
/ start main container
#main{"data-globalscroll" => "false", "data-mobileautofocus" => "true"}
  / shiny graphics
  .pattern.hide-on-phones
  .gradient
  / start container
  .container
    / start header
    #header.row{"data-fixed" => "false"}
      .four.columns
        %h1.logo
          %a{:href => "index.html"}
            %img{:src => "#{root_path}assets/logo.png"}/
        / fake loadbar
        .bar
      .eight.columns
        / start social icons
        .row
          %ul.social
            %li.facebook
              %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank", :title => "facebook"}
            %li.twitter
              %a{:href => "https://twitter.com/@serv_ing", :target => "_blank", :title => "twitter"}
        / end social icons
        / start navigation
        %nav.row
          %ul.nav-bar
            %li
              %a.main{:href => "/", :target => "_self"} Inicio
              / <div class="flyout-toggle"><span></span></div>
              / ejemplo submenu
              / <div class="flyout small">
              / <ul>
              / <li><a href="reel.html">Showreel</a></li>
              / </ul>
              / </div>
              / end submenu
            %li= link_to('Proyectos', proyectos_path, { :class => 'main', :target => '_self' })
            %li
              %a.main{:href => "soluciones", :target => "_self"} Soluciones
            %li
              %a.main{:href => "properties", :target => "_self"} Propiedades
            %li
              %a.main{:href => "contacto", :target => "_self"} Contacto
      / end navigation
    / header end
  / container end
  / start content

app/views/layouts/application.html.haml
!!!!
%html
  %head
    %title ServIng
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:content => "width=device-width", :name => "viewport"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Vehiculos BHD"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %script{:src => "http://maps.google.com/maps/api/js?sensor=false", :type => "text/javascript"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / %script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}
    %link{:href => "images/favicon/favicon.png", :rel => "icon", :type => "image/png"}
    %link{:href => "images/favicon/favicon.png", :rel => "apple-touch-icon"}
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:100,300,400,900", :rel => "stylesheet", :type => "text/css"}
    = yield(:head)
  %body
    %header
      = render :partial => 'layouts/header'
    = yield
    %footer
      = render :partial => 'layouts/footer'

app/views/properties/index.html.haml
#content
  .wrapper
    .old
    .new
      .target.docked.blog
        .gapProperties
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .nine.columns
                - @properties.each do |property|
                  %article.row
                    .meta.four.columns
                      %h4
                        %time= property.title
                      %ul
                        %li
                          %span.tags
                          %b Ubicación:
                          = property.location
                        %li
                          %span.comments
                          %b Tipo:
                          = property.purpose
                        %li
                          %span.meters
                          %b Metros:
                          = property.normalize_meters
                        %li
                          %span.price
                          %b Precio:
                          = property.humanize_price
                        %li
                          %span.habitaciones
                          %b Habitaciones:
                          = property.rooms
                        %li
                          %span.bathrooms
                          %b Baños:
                          = property.bathrooms
                        %li
                          %span.parkingspace
                          %b Parqueos:
                          = property.parkingspace
                    .post.eight.columns.phone-four
                      .image
                        = link_to(image_tag(property.pictures[0].path.full_size.url), property_path(property), :class => 'pull-right', :target => "_self")
                        %span
                      %p= property.description
                      %nice.small.radius.right= link_to(image_tag("properties/LeerMas.png"), property_path(property), :class => 'pull-right', :target => "_self")
                .row
                  .eight.columns.offset-by-four.phone-four
                    %br
                      %hr
                        = will_paginate(@properties, :next_label => '&#187;', :previous_label => '&#171;', :class => 'pull-right pagination', :target => "_self")
              %aside.sidebar.three.columns
                .search
                  %h4 Búsqueda
                  %form.row.nice
                    %input.twelve.column.phone-four.input-text.field{:name => "search", :placeholder => "Search..."}
                      %input.submit{:disabled => "true", :type => "submit", :value => "Search"}
                .textWidget
                  %h4 Propiedades
                  %p En este espacio mantendremos ofertas de propiedades de oportunidad que estaremos promocionando.
              .row.copy
                %p
                  © Todos los derechos reservados, Serv-Ing 2013 -
                  %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                  Powered by
                  %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree

app/views/properties/show.html.haml
#content
  .wrapper
    .old
    .new
      .target.docked.blog
        .gapProperties
        #shell.wide{"data-iscroll" => "true"}
          #scroller.container
            .row
              .nine.columns
                - @property
                %article.row
                  .meta.four.columns
                    %ul.topmargin
                      %li
                        %span.tags
                        %b Ubicación:
                        = @property.location
                      %li
                        %span.comments
                        %b Tipo:
                        = @property.purpose
                      %li
                        %span.meters
                        %b Metros:
                        = @property.normalize_meters
                      %li
                        %span.price
                        %b Precio:
                        = @property.price
                      %li
                        %span.habitaciones
                        %b Habitaciones:
                        = @property.rooms
                      %li
                        %span.bathrooms
                        %b Baños:
                        = @property.bathrooms
                      %li
                        %span.parkingspace
                        %b Parqueos:
                        = @property.parkingspace
                  .post.eight.columns.phone-four
                    .title= @property.title
                    %p= @property.description
                    #galleria
                      - @property.pictures.each_with_index do |picture, index|
                        = link_to("",@property.pictures[index].path.full_size.url)
                        = image_tag(@property.pictures[index].path.full_size.url)
                    :javascript
                      // Load the classic theme
                      Galleria.loadTheme('http://localhost:3000/assets/galleria.classic.min.js');
                      Galleria.configure({
                      showInfo: 'false',
                      imageCrop: true
                      });

                      // Initialize Galleria
                      Galleria.run('#galleria');
                    %nice.small.radius.nice.right= link_to(image_tag("properties/Regresar.png"), properties_path, :class => 'pull-right', :target => "_self")
            .row.copy
              %p
                © Todos los derechos reservados, Serv-Ing 2013 -
                %a{:href => "https://www.facebook.com/pages/Serv-Ing/170998606371283", :target => "_blank"} Conviertete en fan!
                Powered by
                %a{:href => "https://www.facebook.com/pixelpt", :target => "_blank"} Pixel Perfect Tree